type GiscusBooleanString = "0" | "1";
type GiscusInputPosition = "top" | "bottom";
type GiscusMapping = "url" | "title" | "og:title" | "specific" | "number" | "pathname";
type GiscusTheme = "light" | "light_high_contrast" | "light_protanopia" | "light_tritanopia" | "dark" | "dark_high_contrast" | "dark_protanopia" | "dark_tritanopia" | "dark_dimmed" | "transparent_dark" | "preferred_color_scheme";
type GiscusAvailableLanguage = "de" | "gsw" | "en" | "es" | "fr" | "id" | "it" | "ja" | "ko" | "nl" | "pl" | "pt" | "ro" | "ru" | "tr" | "vi" | "zh-CN" | "zh-TW";
type GiscusLoading = "lazy" | "eager";
export type GiscusConfig = {
    id?: string;
    host?: string;
    repo: string;
    repoId: string;
    category?: string;
    categoryId?: string;
    mapping: GiscusMapping;
    term?: string;
    theme?: GiscusTheme;
    strict?: GiscusBooleanString;
    reactionsEnabled?: GiscusBooleanString;
    emitMetadata?: GiscusBooleanString;
    inputPosition?: GiscusInputPosition;
    lang?: GiscusAvailableLanguage;
    loading?: GiscusLoading;
};
export {};
